# Generated by Django 5.2.8 on 2025-12-01 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(max_length=50, unique=True, verbose_name='Cód. Devedor')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_pessoa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo Pessoa')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_titulo_externo', models.CharField(max_length=50, unique=True, verbose_name='Cód. Título')),
                ('numero_doc', models.CharField(max_length=50, verbose_name='Nosso Número')),
                ('dt_vencimento', models.DateField(verbose_name='Vencimento')),
                ('dt_emissao', models.DateField(verbose_name='Emissão')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Original')),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Atual')),
                ('status', models.CharField(choices=[('ABERTO', 'Em Aberto'), ('ACORDO', 'Em Acordo'), ('PAGO', 'Pago')], default='ABERTO', max_length=20)),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='core.devedor')),
            ],
        ),
    ]
