# Generated by Django 5.2.8 on 2025-12-02 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Importado'),
        ),
        migrations.CreateModel(
            name='HistoricoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('LIGACAO', '📞 Ligação'), ('WHATSAPP', '📱 WhatsApp'), ('EMAIL', '📧 E-mail'), ('SISTEMA', '⚙️ Sistema')], default='LIGACAO', max_length=20)),
                ('anotacao', models.TextField(verbose_name='Anotação')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.titulo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
