# Generated by Django 5.2.8 on 2025-12-02 20:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_titulo_saldo_atual_historicocontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multa_percentual', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Valor percentual da multa (ex: 2.00 para 2%).', max_digits=5, verbose_name='Multa (%) por Atraso')),
                ('juros_mensal_percentual', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Valor percentual dos juros ao mês (ex: 1.00 para 1%).', max_digits=5, verbose_name='Juros (%) ao Mês')),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configurações Financeiras',
            },
        ),
    ]
