# Generated by Django 5.2.8 on 2026-05-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaofinanceira'),
    ]

    operations = [
        migrations.AddField(
            model_name='devedor',
            name='pessoa_contato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato'),
        ),
    ]
